CREATE DATABASE IF NOT EXISTS depannage_cdl;
USE depannage_cdl;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS depannages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  num_machine VARCHAR(50) NOT NULL,
  type_machine VARCHAR(120) DEFAULT NULL,
  date_depannage DATE NOT NULL,
  client VARCHAR(120) DEFAULT NULL,
  tel VARCHAR(40) DEFAULT NULL,
  interlocuteur VARCHAR(120) DEFAULT NULL,
  adresse TEXT DEFAULT NULL,
  symptomes TEXT NOT NULL,
  technicien VARCHAR(120) DEFAULT NULL,
  statut ENUM('EN_COURS','RESOLU') NOT NULL DEFAULT 'EN_COURS',
  cause TEXT DEFAULT NULL,
  solution TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at DATETIME DEFAULT NULL
);

INSERT IGNORE INTO users (username, password)
VALUES ('admin', '$2y$10$E0WVK6yS40oIE/uITri5.uavq0nA2c9N9cLgc6LZF0lhqxE0XccJ2');
